INSERT INTO Players (name , country , post , goals) VALUES
('alireza biranvand' , 'iran' , 'goalkeeper' , '0') ,
('sardar azmoun' , 'iran' , 'forward' , '24') ,
('reza quchan nezhad' , 'iran' , 'forward' , '16') ,
('lionel messi' , 'argentina' , 'forward' , '40') ,
('cristiano ronaldo' , 'portugal' , 'forward' , '40') ,
('sergio ramos' , 'spain' , 'defender' , '32') ,
('bernardo silva' , 'portugal' , 'halfback' , '20') ,
('karim benzema' , 'france' , 'forward' , '35') ,
('edouard mendy' , 'senegal' , 'goalkeeper' , '0') ,
('jerard pique' , 'spain' , 'defender' , '19') ,
('mehdi taremi' , 'iran' , 'forward' , '45') ,
('ramin rezaeian' , 'iran' , 'defender' , '22') ,
('iker casaillas' , 'spain' , 'goalkeeper' , '0') ,
('loka modric' , 'croatia' , 'halfback' , '33') ,
('ali karimi' , 'iran' , 'halfback' , '50') ,
('ali daei' , 'iran' , 'forward' , '55') ,
('harry kane' , 'england' , 'forward' , '25') ,
('donnarumma' , 'italy' , 'goalkeeper' , '0') ,
('neymar' , 'brazil' , 'forward' , '38') ,
('mehdi mahdavi kia' , 'iran' , 'halfback' , '28') ;